HR_PERSONA_ID = 105

HR_TEST_CASES = [
    {
        "query": "apply for a visa letter for switzerland, addressed to the swiss embassy",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Request Visa Letter"],
        "expect_form": True,
        "expected_form_title": "Visa Letter",
        "enabled": True,
    },
    {
        "query": "show my performance report",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Performance Review Report"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "get my last performance review",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Performance Review Report"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "what are my benefits",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Employee Benefits"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "show my insurance and benefits",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Employee Benefits"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "tell me about company policies",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Benefits Structure"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "what is the leave policy",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Leave Info"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "what courses are available in february",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get LMS Courses"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "show me available training courses",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get LMS Courses"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "submit an overtime request for yesterday for 5 hours, reason: project deadline work",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Request Overtime"],
        "expect_form": True,
        "expected_form_title": "Overtime Request",
        "enabled": True,
    },
    {
        "query": "submit an overtime claim for 7 hours worked on the system go live event yesterday, reason: system go live support",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Request Overtime"],
        "expect_form": True,
        "expected_form_title": "Overtime Request",
        "enabled": True,
    },
    {
        "query": "give my leave balance",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Leave Info"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "how many leave days do i have left",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Leave Info"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "apply for annual leave from february 1 to february 5, 5 days, reason: personal travel",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Apply Leave"],
        "expect_form": True,
        "expected_form_title": "Apply Leave",
        "enabled": True,
    },
    {
        "query": "apply for sick leave for tomorrow, 1 day, reason: fever and not feeling well",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Apply Leave"],
        "expect_form": True,
        "expected_form_title": "Apply Leave",
        "enabled": True,
    },
    {
        "query": "apply for casual leave on march 10, 1 day, reason: personal work",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Apply Leave"],
        "expect_form": True,
        "expected_form_title": "Apply Leave",
        "enabled": True,
    },
    {
        "query": "apply for paternity leave starting next monday for 30 days, reason: newborn baby care",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Apply Leave"],
        "expect_form": True,
        "expected_form_title": "Apply Leave",
        "enabled": True,
    },
    {
        "query": "get my payslip for last month",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Payslip"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "show my payslip for february 2026",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Payslip"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "apply for a bank letter for a car loan addressed to the bank manager at QNB",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Bank Letter"],
        "expect_form": True,
        "expected_form_title": "Bank Letter",
        "enabled": True,
    },
    {
        "query": "generate a salary transfer letter for qatar national bank QNB addressed to the branch manager",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Bank Letter"],
        "expect_form": True,
        "expected_form_title": "Bank Letter",
        "enabled": True,
    },
    {
        "query": "generate a bank letter for a credit card application addressed to the bank manager at commercial bank of qatar",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Bank Letter"],
        "expect_form": True,
        "expected_form_title": "Bank Letter",
        "expected_fields": ["Credit Card", "Bank", "Manager"],
        "enabled": True,
    },
    {
        "query": "i need a personal loan bank letter addressed to the branch manager at doha bank for a personal loan application",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Bank Letter"],
        "expect_form": True,
        "expected_form_title": "Bank Letter",
        "expected_fields": ["Personal Loan", "Doha Bank"],
        "enabled": True,
    },
    {
        "query": "create a salary transfer letter for qatar national bank addressed to the branch manager for my salary account",
        "persona_id": HR_PERSONA_ID,
        "expected_tools": ["Get Bank Letter"],
        "expect_form": True,
        "expected_form_title": "Bank Letter",
        "expected_fields": ["Salary Transfer", "Qatar National Bank"],
        "enabled": True,
    },
]