TENDER_PERSONA_ID = 131

TENDER_TEST_CASES = [
    {
        "query": "what are the tender documents i have",
        "persona_id": TENDER_PERSONA_ID,
        "expected_tools": ["List Tender Documents"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "what is the icv of the tenders",
        "persona_id": TENDER_PERSONA_ID,
        "expected_tools": ["List Tender Documents", "Search Tender Documents"],
        "expect_form": False,
        "enabled": True,
    },
    {
        "query": "what are the risks of each tender",
        "persona_id": TENDER_PERSONA_ID,
        "expected_tools": ["List Tender Documents", "Search Tender Documents"],
        "expect_form": False,
        "enabled": True,
    },
    
    {
    "query": "what are the tender documents i have",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "what is the icv of the tenders",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents", "Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "what are the risks of each tender",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents", "Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "show me the last 5 tender documents",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "find the submission deadline in the Ministry of Justice tender",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "what are the technical specifications for hardware in Black Arrow tender",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "list all available tender documents and find the payment terms in each",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents", "Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "do I have any tender documents related to construction",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "search for warranty requirements across all tenders",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents", "Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "what is the bid validity period in the AV Tech BOQ tender",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "how many tender documents are in the system",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "compare the evaluation criteria across all tenders",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["List Tender Documents", "Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
{
    "query": "find insurance requirements in the Ministry tender document",
    "persona_id": TENDER_PERSONA_ID,
    "expected_tools": ["Search Tender Documents"],
    "expect_form": False,
    "enabled": True,
},
]