import type { ThemeDraft } from "./themeDraft";
import { buildCssText } from "./applyOverrides";

const FILE_HEADER = `/* Generated by Theme Editor — paste over the token blocks in src/index.css */\n\n`;

export function buildFullThemeCss(draft: ThemeDraft): string {
  return FILE_HEADER + buildCssText(draft);
}

export function downloadThemeCss(draft: ThemeDraft, filename = "theme.css"): void {
  const content = buildFullThemeCss(draft);
  const blob = new Blob([content], { type: "text/css" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
