import {
  Plane,
  Hotel,
  UtensilsCrossed,
  Mail,
  MailSearch,
  MailOpen,
  Search,
  Code,
  Database,
  FileText,
  FileSearch,
  Files,
  Settings,
  Globe,
  Calendar,
  CalendarDays,
  Users,
  ShoppingCart,
  DollarSign,
  TrendingUp,
  MessageSquare,
  Bell,
  Archive,
  BookOpen,
  Briefcase,
  Camera,
  Clock,
  CreditCard,
  Edit,
  Heart,
  Home,
  MapPin,
  Map,
  Route,
  Package,
  Phone,
  Clipboard,
  FileSpreadsheet,
  BarChart,
  PieChart,
  LineChart,
  Folder,
  FolderOpen,
  Download,
  Upload,
  Share2,
  Link,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  Speaker,
  Wifi,
  Bluetooth,
  Battery,
  Zap,
  Sun,
  Moon,
  CloudRain,
  Cloud,
  Wind,
  Thermometer,
  Droplet,
  Umbrella,
  Car,
  Train,
  Bus,
  Bike,
  Ship,
  Truck,
  AlertCircle,
  CheckCircle,
  Info,
  XCircle,
  AlertTriangle,
  HelpCircle,
  Activity,
  Award,
  Target,
  Compass,
  Filter,
  Flag,
  Gift,
  Key,
  Lock,
  Unlock,
  Shield,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  Save,
  Copy,
  Trash,
  RefreshCw,
  RotateCw,
  Maximize,
  Minimize,
  Printer,
  Scissors,
  Paperclip,
  Bookmark,
  Tag,
  Star,
  ThumbsUp,
  ThumbsDown,
  Eye,
  EyeOff,
  Volume2,
  VolumeX,
  PlayCircle,
  PauseCircle,
  StopCircle,
  SkipForward,
  SkipBack,
  Rewind,
  Forward,
  Reply,
  ReplyAll,
  Send,
  PlaneTakeoff,
  PlaneLanding,
  Sparkles,
  List,
  Send as PaperPlane,
  Building,
  Bed,
  Landmark,
  Brain,
  LucideIcon,
} from "lucide-react";

/**
 * Icon registry mapping string names to Lucide icon components
 * This allows the backend to specify which icon to use for each tool
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  // Travel & Transport
  plane: Plane,
  flight: Plane,
  airline: Plane,
  planetakeoff: PlaneTakeoff,
  flightbooking: PlaneTakeoff,
  flightsearch: Plane,
  planelanding: PlaneLanding,
  hotel: Hotel,
  accommodation: Hotel,
  hotelbooking: Hotel,
  hotelsearch: Hotel,
  amadeushotelbooking: Hotel,
  building: Building,
  bed: Bed,
  car: Car,
  vehicle: Car,
  train: Train,
  bus: Bus,
  bike: Bike,
  bicycle: Bike,
  ship: Ship,
  boat: Ship,
  truck: Truck,

  // Food & Dining
  restaurant: UtensilsCrossed,
  restaurantsearch: UtensilsCrossed,
  food: UtensilsCrossed,
  dining: UtensilsCrossed,
  meal: UtensilsCrossed,

  // Communication
  email: Mail,
  mail: Mail,
  mailsearch: MailSearch,
  emailretrieval: MailSearch,
  mailopen: MailOpen,
  mailcheck: MailOpen,
  getcurrentemail: MailOpen,
  forward: Forward,
  mailforward: Forward,
  gmailforward: Forward,
  reply: Reply,
  mailreply: Reply,
  gmailreply: Reply,
  replyall: ReplyAll,
  mailreplyall: ReplyAll,
  gmailreplyall: ReplyAll,
  send: Send,
  sendemail: Send,
  gmailsend: Send,
  paperplane: PaperPlane,
  paperplaneicon: PaperPlane,
  utensilscrossed: UtensilsCrossed,
  trendingup: TrendingUp,
  message: MessageSquare,
  messagesquare: MessageSquare,
  chat: MessageSquare,
  phone: Phone,
  call: Phone,
  notification: Bell,
  bell: Bell,
  alert: Bell,

  // Technology
  search: Search,
  find: Search,
  code: Code,
  api: Code,
  programming: Code,
  database: Database,
  sql: Database,
  data: Database,
  globe: Globe,
  web: Globe,
  webanalysis: Globe,
  firecrawlwebsearch: Globe,
  websearch: Globe,
  url: Globe,
  internet: Globe,
  website: Globe,
  wifi: Wifi,
  bluetooth: Bluetooth,
  battery: Battery,
  power: Zap,
  zap: Zap,
  energy: Zap,
  brain: Brain,
  ai: Brain,
  intelligence: Brain,
  thinking: Brain,
  mind: Brain,
  neural: Brain,
  neuron: Brain,

  // Documents & Files
  file: FileText,
  filetext: FileText,
  document: FileText,
  documentanalysis: FileText,
  filesearch: FileSearch,
  files: Files,
  listuploadeddocs: Files,
  text: FileText,
  archive: Archive,
  book: BookOpen,
  bookopen: BookOpen,
  read: BookOpen,
  folder: Folder,
  directory: Folder,
  folderopen: FolderOpen,
  spreadsheet: FileSpreadsheet,
  excel: FileSpreadsheet,
  filespreadsheet: FileSpreadsheet,
  clipboard: Clipboard,
  notes: Clipboard,

  // Business & Finance
  briefcase: Briefcase,
  business: Briefcase,
  work: Briefcase,
  calendar: Calendar,
  calendardays: CalendarDays,
  qatarcalendar: Calendar,
  schedule: Calendar,
  date: Calendar,
  users: Users,
  team: Users,
  people: Users,
  shopping: ShoppingCart,
  shoppingcart: ShoppingCart,
  cart: ShoppingCart,
  payment: CreditCard,
  card: CreditCard,
  credit: CreditCard,
  creditcard: CreditCard,
  dollar: DollarSign,
  dollarsign: DollarSign,
  money: DollarSign,
  currency: DollarSign,
  analytics: TrendingUp,
  trending: TrendingUp,
  growth: TrendingUp,
  chart: BarChart,
  bar: BarChart,
  barchart: BarChart,
  htmlchart: BarChart,
  gethtmlchart: BarChart,
  pie: PieChart,
  piechart: PieChart,
  line: LineChart,
  linechart: LineChart,

  // Media
  image: Image,
  photo: Image,
  picture: Image,
  video: Video,
  movie: Video,
  film: Video,
  music: Music,
  audio: Music,
  sound: Music,
  headphones: Headphones,
  mic: Mic,
  microphone: Mic,
  speaker: Speaker,
  volume: Volume2,
  volume2: Volume2,
  mute: VolumeX,
  volumex: VolumeX,
  camera: Camera,

  // Actions
  download: Download,
  upload: Upload,
  share: Share2,
  share2: Share2,
  link: Link,
  save: Save,
  copy: Copy,
  duplicate: Copy,
  trash: Trash,
  delete: Trash,
  remove: Trash,
  refresh: RefreshCw,
  refreshcw: RefreshCw,
  reload: RefreshCw,
  rotate: RotateCw,
  rotatecw: RotateCw,
  edit: Edit,
  modify: Edit,
  update: Edit,
  print: Printer,
  printer: Printer,
  cut: Scissors,
  scissors: Scissors,
  attach: Paperclip,
  paperclip: Paperclip,
  bookmark: Bookmark,
  tag: Tag,
  label: Tag,
  star: Star,
  favorite: Star,
  like: ThumbsUp,
  thumbsup: ThumbsUp,
  dislike: ThumbsDown,
  thumbsdown: ThumbsDown,

  // UI & Navigation
  settings: Settings,
  config: Settings,
  configuration: Settings,
  home: Home,
  location: MapPin,
  mappin: MapPin,
  map: Map,
  maproute: Map,
  route: Route,
  qataritineraries: Map,
  itinerary: Map,
  pin: MapPin,
  marker: MapPin,
  qatarthingstodo: Landmark,
  thingstodo: Landmark,
  landmark: Landmark,
  sparkles: Sparkles,
  list: List,
  clock: Clock,
  time: Clock,
  timer: Clock,
  compass: Compass,
  navigation: Compass,
  filter: Filter,
  flag: Flag,
  maximize: Maximize,
  fullscreen: Maximize,
  minimize: Minimize,
  eye: Eye,
  view: Eye,
  visibility: Eye,
  eyeoff: EyeOff,
  hide: EyeOff,
  hidden: EyeOff,

  // Status & Feedback
  success: CheckCircle,
  check: CheckCircle,
  checkcircle: CheckCircle,
  complete: CheckCircle,
  error: XCircle,
  xcircle: XCircle,
  fail: XCircle,
  warning: AlertTriangle,
  warn: AlertTriangle,
  alerttriangle: AlertTriangle,
  info: Info,
  information: Info,
  help: HelpCircle,
  helpcircle: HelpCircle,
  question: HelpCircle,
  alertcircle: AlertCircle,
  activity: Activity,
  pulse: Activity,
  award: Award,
  trophy: Award,
  target: Target,
  goal: Target,

  // Security & Access
  key: Key,
  lock: Lock,
  locked: Lock,
  unlock: Unlock,
  unlocked: Unlock,
  shield: Shield,
  security: Shield,
  protect: Shield,
  usercheck: UserCheck,
  verified: UserCheck,
  userplus: UserPlus,
  adduser: UserPlus,
  userminus: UserMinus,
  removeuser: UserMinus,
  userx: UserX,
  blockuser: UserX,

  // Weather & Nature
  sun: Sun,
  sunny: Sun,
  moon: Moon,
  night: Moon,
  cloud: Cloud,
  cloudy: Cloud,
  rain: CloudRain,
  rainy: CloudRain,
  cloudrain: CloudRain,
  wind: Wind,
  windy: Wind,
  temperature: Thermometer,
  temp: Thermometer,
  thermometer: Thermometer,
  water: Droplet,
  droplet: Droplet,
  umbrella: Umbrella,

  // Miscellaneous
  gift: Gift,
  present: Gift,
  heart: Heart,
  love: Heart,
  package: Package,
  box: Package,
  parcel: Package,

  // Media Controls
  play: PlayCircle,
  playcircle: PlayCircle,
  pause: PauseCircle,
  pausecircle: PauseCircle,
  stop: StopCircle,
  stopcircle: StopCircle,
  next: SkipForward,
  skipforward: SkipForward,
  previous: SkipBack,
  skipback: SkipBack,
  // forward: Forward,
  backward: Rewind,
};

/**
 * Mapping from registry keys to their camelCase import names
 * This maps the lowercase registry keys to their actual PascalCase import names
 */
const ICON_NAME_MAP: Record<string, string> = {
  // Travel & Transport
  plane: "Plane",
  flight: "Plane",
  airline: "Plane",
  planetakeoff: "PlaneTakeoff",
  flightbooking: "PlaneTakeoff",
  flightsearch: "Plane",
  planelanding: "PlaneLanding",
  hotel: "Hotel",
  accommodation: "Hotel",
  hotelbooking: "Hotel",
  hotelsearch: "Hotel",
  amadeushotelbooking: "Hotel",
  building: "Building",
  bed: "Bed",
  car: "Car",
  vehicle: "Car",
  train: "Train",
  bus: "Bus",
  bike: "Bike",
  bicycle: "Bike",
  ship: "Ship",
  boat: "Ship",
  truck: "Truck",
  
  // Food & Dining
  restaurant: "UtensilsCrossed",
  restaurantsearch: "UtensilsCrossed",
  food: "UtensilsCrossed",
  dining: "UtensilsCrossed",
  meal: "UtensilsCrossed",
  utensilscrossed: "UtensilsCrossed",
  
  // Communication
  email: "Mail",
  mail: "Mail",
  mailsearch: "MailSearch",
  emailretrieval: "MailSearch",
  mailopen: "MailOpen",
  mailcheck: "MailOpen",
  getcurrentemail: "MailOpen",
  forward: "Forward",
  mailforward: "Forward",
  gmailforward: "Forward",
  reply: "Reply",
  mailreply: "Reply",
  gmailreply: "Reply",
  replyall: "ReplyAll",
  mailreplyall: "ReplyAll",
  gmailreplyall: "ReplyAll",
  send: "Send",
  sendemail: "Send",
  gmailsend: "Send",
  paperplane: "PaperPlane",
  paperplaneicon: "PaperPlane",
  message: "MessageSquare",
  messagesquare: "MessageSquare",
  chat: "MessageSquare",
  phone: "Phone",
  call: "Phone",
  notification: "Bell",
  bell: "Bell",
  alert: "Bell",
  
  // Technology
  search: "Search",
  find: "Search",
  code: "Code",
  api: "Code",
  programming: "Code",
  database: "Database",
  sql: "Database",
  data: "Database",
  globe: "Globe",
  web: "Globe",
  webanalysis: "Globe",
  firecrawlwebsearch: "Globe",
  websearch: "Globe",
  url: "Globe",
  internet: "Globe",
  website: "Globe",
  wifi: "Wifi",
  bluetooth: "Bluetooth",
  battery: "Battery",
  power: "Zap",
  zap: "Zap",
  energy: "Zap",
  brain: "Brain",
  ai: "Brain",
  intelligence: "Brain",
  thinking: "Brain",
  mind: "Brain",
  neural: "Brain",
  neuron: "Brain",
  
  // Documents & Files
  file: "FileText",
  filetext: "FileText",
  document: "FileText",
  documentanalysis: "FileText",
  filesearch: "FileSearch",
  files: "Files",
  listuploadeddocs: "Files",
  text: "FileText",
  archive: "Archive",
  book: "BookOpen",
  bookopen: "BookOpen",
  read: "BookOpen",
  folder: "Folder",
  directory: "Folder",
  folderopen: "FolderOpen",
  spreadsheet: "FileSpreadsheet",
  excel: "FileSpreadsheet",
  filespreadsheet: "FileSpreadsheet",
  clipboard: "Clipboard",
  notes: "Clipboard",
  
  // Business & Finance
  briefcase: "Briefcase",
  business: "Briefcase",
  work: "Briefcase",
  calendar: "Calendar",
  calendardays: "CalendarDays",
  qatarcalendar: "Calendar",
  schedule: "Calendar",
  date: "Calendar",
  users: "Users",
  team: "Users",
  people: "Users",
  shopping: "ShoppingCart",
  shoppingcart: "ShoppingCart",
  cart: "ShoppingCart",
  payment: "CreditCard",
  card: "CreditCard",
  credit: "CreditCard",
  creditcard: "CreditCard",
  dollar: "DollarSign",
  dollarsign: "DollarSign",
  money: "DollarSign",
  currency: "DollarSign",
  analytics: "TrendingUp",
  trending: "TrendingUp",
  growth: "TrendingUp",
  trendingup: "TrendingUp",
  chart: "BarChart",
  bar: "BarChart",
  barchart: "BarChart",
  htmlchart: "BarChart",
  gethtmlchart: "BarChart",
  pie: "PieChart",
  piechart: "PieChart",
  line: "LineChart",
  linechart: "LineChart",
  
  // Media
  image: "Image",
  photo: "Image",
  picture: "Image",
  video: "Video",
  movie: "Video",
  film: "Video",
  music: "Music",
  audio: "Music",
  sound: "Music",
  headphones: "Headphones",
  mic: "Mic",
  microphone: "Mic",
  speaker: "Speaker",
  volume: "Volume2",
  volume2: "Volume2",
  mute: "VolumeX",
  volumex: "VolumeX",
  camera: "Camera",
  
  // Actions
  download: "Download",
  upload: "Upload",
  share: "Share2",
  share2: "Share2",
  link: "Link",
  save: "Save",
  copy: "Copy",
  duplicate: "Copy",
  trash: "Trash",
  delete: "Trash",
  remove: "Trash",
  refresh: "RefreshCw",
  refreshcw: "RefreshCw",
  reload: "RefreshCw",
  rotate: "RotateCw",
  rotatecw: "RotateCw",
  edit: "Edit",
  modify: "Edit",
  update: "Edit",
  print: "Printer",
  printer: "Printer",
  cut: "Scissors",
  scissors: "Scissors",
  attach: "Paperclip",
  paperclip: "Paperclip",
  bookmark: "Bookmark",
  tag: "Tag",
  label: "Tag",
  star: "Star",
  favorite: "Star",
  like: "ThumbsUp",
  thumbsup: "ThumbsUp",
  dislike: "ThumbsDown",
  thumbsdown: "ThumbsDown",
  
  // UI & Navigation
  settings: "Settings",
  config: "Settings",
  configuration: "Settings",
  home: "Home",
  location: "MapPin",
  mappin: "MapPin",
  map: "Map",
  maproute: "Map",
  route: "Route",
  qataritineraries: "Map",
  itinerary: "Map",
  pin: "MapPin",
  marker: "MapPin",
  qatarthingstodo: "Landmark",
  thingstodo: "Landmark",
  landmark: "Landmark",
  sparkles: "Sparkles",
  list: "List",
  clock: "Clock",
  time: "Clock",
  timer: "Clock",
  compass: "Compass",
  navigation: "Compass",
  filter: "Filter",
  flag: "Flag",
  maximize: "Maximize",
  fullscreen: "Maximize",
  minimize: "Minimize",
  eye: "Eye",
  view: "Eye",
  visibility: "Eye",
  eyeoff: "EyeOff",
  hide: "EyeOff",
  hidden: "EyeOff",
  
  // Status & Feedback
  success: "CheckCircle",
  check: "CheckCircle",
  checkcircle: "CheckCircle",
  complete: "CheckCircle",
  error: "XCircle",
  xcircle: "XCircle",
  fail: "XCircle",
  warning: "AlertTriangle",
  warn: "AlertTriangle",
  alerttriangle: "AlertTriangle",
  info: "Info",
  information: "Info",
  help: "HelpCircle",
  helpcircle: "HelpCircle",
  question: "HelpCircle",
  alertcircle: "AlertCircle",
  activity: "Activity",
  pulse: "Activity",
  award: "Award",
  trophy: "Award",
  target: "Target",
  goal: "Target",
  
  // Security & Access
  key: "Key",
  lock: "Lock",
  locked: "Lock",
  unlock: "Unlock",
  unlocked: "Unlock",
  shield: "Shield",
  security: "Shield",
  protect: "Shield",
  usercheck: "UserCheck",
  verified: "UserCheck",
  userplus: "UserPlus",
  adduser: "UserPlus",
  userminus: "UserMinus",
  removeuser: "UserMinus",
  userx: "UserX",
  blockuser: "UserX",
  
  // Weather & Nature
  sun: "Sun",
  sunny: "Sun",
  moon: "Moon",
  night: "Moon",
  cloud: "Cloud",
  cloudy: "Cloud",
  rain: "CloudRain",
  rainy: "CloudRain",
  cloudrain: "CloudRain",
  wind: "Wind",
  windy: "Wind",
  temperature: "Thermometer",
  temp: "Thermometer",
  thermometer: "Thermometer",
  water: "Droplet",
  droplet: "Droplet",
  umbrella: "Umbrella",
  
  // Miscellaneous
  gift: "Gift",
  present: "Gift",
  heart: "Heart",
  love: "Heart",
  package: "Package",
  box: "Package",
  parcel: "Package",
  
  // Media Controls
  play: "PlayCircle",
  playcircle: "PlayCircle",
  pause: "PauseCircle",
  pausecircle: "PauseCircle",
  stop: "StopCircle",
  stopcircle: "StopCircle",
  next: "SkipForward",
  skipforward: "SkipForward",
  previous: "SkipBack",
  skipback: "SkipBack",
  backward: "Rewind",
};

/**
 * Get icon component by exact name from backend
 * @param iconName - Icon name from backend (e.g., "email", "flight", "calendar")
 * @returns Lucide icon component or Settings as fallback
 */
export const getIconByName = (iconName: string): LucideIcon => {
  if (!iconName) return Settings;
  
  const normalizedName = iconName.toLowerCase().trim().replaceAll(/[\s_-]/g, "");
  return ICON_REGISTRY[normalizedName] || Settings;
};

/**
 * Get camelCase import name from registry key
 * @param registryKey - Registry key (e.g., "email", "brain", "mailsearch")
 * @returns CamelCase import name (e.g., "Mail", "Brain", "MailSearch") or empty string
 */
export const getIconImportName = (registryKey: string): string => {
  if (!registryKey) return "";
  
  const normalizedKey = registryKey.toLowerCase().trim().replaceAll(/[\s_-]/g, "");
  return ICON_NAME_MAP[normalizedKey] || "";
};

/**
 * Convert camelCase import name back to registry key
 * This is used when receiving icon names from backend that are in camelCase format
 * @param importName - CamelCase import name (e.g., "Mail", "PlaneTakeoff", "MailSearch")
 * @returns Registry key (e.g., "mail", "planetakeoff", "mailsearch") or the original value if not found
 */
export const getRegistryKeyFromImportName = (importName: string): string => {
  if (!importName) return "";
  
  // First, try to find exact match in reverse
  const normalizedInput = importName.toLowerCase().trim().replaceAll(/[\s_-]/g, "");
  
  // Check if it's already a registry key
  if (ICON_REGISTRY[normalizedInput]) {
    return normalizedInput;
  }
  
  // Create reverse map on the fly (import name -> first registry key that maps to it)
  // We'll prefer the most canonical key (usually the first one alphabetically)
  for (const [key, value] of Object.entries(ICON_NAME_MAP)) {
    if (value.toLowerCase() === normalizedInput || value === importName) {
      return key;
    }
  }
  
  // If not found, return normalized version (might be a custom icon name)
  return normalizedInput;
};

// Export Settings icon for use as fallback
export { Settings } from "lucide-react";

